---
title: "Supplemental Figures"
author: "E Schlatter"
date: "6/27/2022"
output: html_document
---
## Relationship between SL and Ucrit

```{r}
library(lme4)
phens2 = subset(phens,is.na(speed)==FALSE) #dataset without nas
null_lengthspeed = lm(speed~length,data=phens2) #use length to predict speed
null2_lengthspeed = lmer(speed~(1|clutch),data=phens2) #use clutch to predict speed
lengthspeed = lmer(speed ~ length + (1|clutch), data=phens2) #use length and clutch to predict speed

summary(lengthspeed)

##use bootstrapping and a likelihood ratio test to check the significance of clutch
# https://towardsdatascience.com/random-effects-in-linear-models-15845b2540ac
my_stat = 2*(logLik(lengthspeed)-logLik(null_lengthspeed,REML=TRUE))
  #likelihood ratio of length+clutch model vs length model, using actual data
LRT_stat = numeric(1000)
#now calculate the likelihood ratio of length+clutch model vs length model for 1000 simulated datasets where clutch has no effect
for(i in 1:1000){
  y=simulate(null_lengthspeed)$sim_1 #simulate according to the null hypothesis (clutch has no effect, only length does)
  null_md = lm(y~length,data=phens2) 
  mixed_md = lmer(y~length+(1|clutch),data=phens2)
  LRT_stat[i] = as.numeric(2*(logLik(mixed_md)-logLik(null_md,REML=TRUE))) #get the likelihood ratio (log-likelihood ratio probably close to 0, because including clutch shouldn't improve the model fit to the dataset simulated without clutch effects)
}
  #get warnings about singularity in model fitting (from the mixed model, I assume -- this is unsurprising)
sum(LRT_stat>my_stat) #zero -- very significant
## --> clutch is important! The likelihood ratio of the model including clutch to the model not including it is very high, compared to what we'd expect from data from this experimental design if there was actually no effect of clutch

##same to check the significance of length
my_stat = 2*(logLik(lengthspeed)-logLik(null2_lengthspeed,REML=TRUE)) #likelihood ratio
LRT_stat = numeric(1000)
for(i in 1:1000){
  y=simulate(null2_lengthspeed)$sim_1
  null_md = lmer(y~(1|clutch),data=phens2)
  mixed_md = lmer(y~length+(1|clutch),data=phens2)
  LRT_stat[i] = as.numeric(2*(logLik(mixed_md)-logLik(null_md,REML=TRUE)))
}
  #no complaints about singularity this time. I guess that's because y (the simulated data) is different: it assumes there's a clutch effect.
sum(LRT_stat > my_stat) #107/1000 -- not significant

summary(lengthspeed)

ggplot(phens,aes(x=length,y=speed,color=clutch))+
  geom_point()
```


## Use SL as a covariate for Ucrit

### With parental effects
Original analysis: Ucrit~age+animal+dam+sire+clutch+units
```{r}
#from tuto_en; with residual edited (nu=0.002 instead of nu=1) to be proper
prior_expand<-list(R=list(V=1,nu=0.002),
                G=list(G1=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G2=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G3=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G4=list(V=1,nu=1,alpha.mu=0,alpha.V=1000)))

Ucrit_parent <- MCMCglmm(speed~1+age,
                              random=~animal+clutch+dam+sire,
                              prior=prior_expand,
                              ginverse=list(animal=Ainv),
                              data=phens,nitt=100000,burnin=1000,thin=10,verbose=TRUE)
model_results(Ucrit_parent)
```

```{r}
#from tuto_en; with residual edited (nu=0.002 instead of nu=1) to be proper
prior_expand<-list(R=list(V=1,nu=0.002),
                G=list(G1=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G2=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G3=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G4=list(V=1,nu=1,alpha.mu=0,alpha.V=1000)))

#give parents SL of 0 (because MCMCglmm complains if fixed effect predictor doesn't have a value for each observation)
phens_edit=phens
for(i in 1:nrow(phens)){
  if(is.na(phens$length[i])) phens_edit$length[i]=0
}

Ucrit_parent_withSL <- MCMCglmm(speed~1+age+length,
                              random=~animal+clutch+dam+sire,
                              prior=prior_expand,
                              ginverse=list(animal=Ainv),
                              data=phens_edit,nitt=100000,burnin=1000,thin=10,verbose=FALSE)
model_results(Ucrit_parent_withSL)
```


### No parental effects
Original analysis: Ucrit~age+animal+clutch+units
```{r}
#from tuto_en; with residual edited (nu=0.002 instead of nu=1) to be proper
prior_expand<-list(R=list(V=1,nu=0.002),
                G=list(G1=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G2=list(V=1,nu=1,alpha.mu=0,alpha.V=1000)))

Ucrit_noparent <- MCMCglmm(speed~1+age,
                              random=~animal+clutch,
                              prior=prior_expand,
                              ginverse=list(animal=Ainv),
                              data=phens,nitt=100000,burnin=1000,thin=10,verbose=TRUE)
model_results(Ucrit_noparent)
```

Compare with using SL as a fixed effect: Ucrit~age+SL+animal+clutch+units
```{r}
#from tuto_en; with residual edited (nu=0.002 instead of nu=1) to be proper
prior_expand<-list(R=list(V=1,nu=0.002),
                G=list(G1=list(V=1,nu=1,alpha.mu=0,alpha.V=1000),
                       G2=list(V=1,nu=1,alpha.mu=0,alpha.V=1000)))

#give parents SL of 0 (because MCMCglmm complains if fixed effect predictor doesn't have a value for each observation)
phens_edit=phens
for(i in 1:nrow(phens)){
  if(is.na(phens$length[i])) phens_edit$length[i]=0
}

Ucrit_noparent_withSL <- MCMCglmm(speed~1+age+length,
                              random=~animal+clutch,
                              prior=prior_expand,
                              ginverse=list(animal=Ainv),
                              data=phens_edit,nitt=100000,burnin=1000,thin=10,verbose=TRUE)
model_results(Ucrit_noparent_withSL)
```