---
title: "Process data and run models"
author: "E Schlatter"
date: "12/18/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(MasterBayes) #for pedigree functions
library(MCMCglmm) #for running the model
library(MCMCpack) #for inverse wishart distributions
library(bayesplot) #mcmc_areas plot function
```

```{r}
source("../functions/model_fns.R")
source("priors.R")
```

## Run models

```{r, eval=FALSE}
##test to make sure it works
param_list=prior_invgamma2_params
model_statement="animal+clutch"
n_vars=2 #not including the residual (units)
n_mcmc_iter=100000


model <- model_run(prior_invgamma2_params,'speed',"animal+clutch",2,1000)
save(model,file='../model_runs/test.RData')
diagn <- model_diagnostics(model)
results <- model_results(model)
```

## Full dataset models

```{r}
### SL, no parental effects

#prior_expand
SL_noparent_fulldata_priorexpand_10e5 <- model_run(prior_expand_params,'length',"animal+clutch",2,100000)

#prior_ext
SL_noparent_fulldata_priorext_10e5 <- model_run(prior_ext_params,'length',"animal+clutch",2,100000)

#invgamma
SL_noparent_fulldata_invgamma_10e5 <- model_run(prior_invgamma_params,'length',"animal+clutch",2,100000)

#invgamma2
SL_noparent_fulldata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'length',"animal+clutch",2,100000)

#flat
SL_noparent_fulldata_flatprior_10e5 <- model_run(prior_flat_params,'length',"animal+clutch",2,100000)

#save them as a list
SL_noparent_fulldata_10e5 <- list(SL_noparent_fulldata_priorexpand_10e5,SL_noparent_fulldata_priorext_10e5,
                                  SL_noparent_fulldata_invgamma_10e5,SL_noparent_fulldata_invgamma2_10e5,
                                  SL_noparent_fulldata_flatprior_10e5)
save(SL_noparent_fulldata_10e5,file='../model_runs/SL_noparent_fulldata_10e5.RData')


### SL, with parental effects

#prior_expand
SL_parent_fulldata_priorexpand_10e5 <- model_run(prior_expand_params,'length',"animal+clutch+dam+sire",4,100000)

#prior_ext
SL_parent_fulldata_priorext_10e5 <- model_run(prior_ext_params,'length',"animal+clutch+dam+sire",4,100000)

#invgamma
SL_parent_fulldata_invgamma_10e5 <- model_run(prior_invgamma_params,'length',"animal+clutch+dam+sire",4,100000)

#invgamma2
SL_parent_fulldata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'length',"animal+clutch+dam+sire",4,100000)

#flat -- doesn't work; remove it
# SL_parent_fulldata_flatprior_10e5 <- model_run(prior_flat_params,'length',"animal+clutch+dam+sire",4,100000)

#save them as a list
SL_parent_fulldata_10e5 <- list(SL_parent_fulldata_priorexpand_10e5,SL_parent_fulldata_priorext_10e5,
                                  SL_parent_fulldata_invgamma_10e5,SL_parent_fulldata_invgamma2_10e5)
save(SL_parent_fulldata_10e5,file='../model_runs/SL_parent_fulldata_10e5.RData')


### Ucrit, no parental effects

#prior_expand
Ucrit_noparent_fulldata_priorexpand_10e5 <- model_run(prior_expand_params,'speed',"animal+clutch",2,100000)

#prior_ext
Ucrit_noparent_fulldata_priorext_10e5 <- model_run(prior_ext_params,'speed',"animal+clutch",2,100000)

#invgamma
Ucrit_noparent_fulldata_invgamma_10e5 <- model_run(prior_invgamma_params,'speed',"animal+clutch",2,100000)

#invgamma2
Ucrit_noparent_fulldata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'speed',"animal+clutch",2,100000)

#flat
Ucrit_noparent_fulldata_flatprior_10e5 <- model_run(prior_flat_params,'speed',"animal+clutch",2,100000)

#save them as a list
Ucrit_noparent_fulldata_10e5 <- list(Ucrit_noparent_fulldata_priorexpand_10e5,Ucrit_noparent_fulldata_priorext_10e5,
                                  Ucrit_noparent_fulldata_invgamma_10e5,Ucrit_noparent_fulldata_invgamma2_10e5,
                                  Ucrit_noparent_fulldata_flatprior_10e5)
save(Ucrit_noparent_fulldata_10e5,file='../model_runs/Ucrit_noparent_fulldata_10e5.RData')


### Ucrit, with parental effects

#prior_expand
Ucrit_parent_fulldata_priorexpand_10e5 <- model_run(prior_expand_params,'speed',"animal+clutch+dam+sire",4,100000)

#prior_ext
Ucrit_parent_fulldata_priorext_10e5 <- model_run(prior_ext_params,'speed',"animal+clutch+dam+sire",4,100000)

#invgamma
Ucrit_parent_fulldata_invgamma_10e5 <- model_run(prior_invgamma_params,'speed',"animal+clutch+dam+sire",4,100000)

#invgamma2
Ucrit_parent_fulldata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'speed',"animal+clutch+dam+sire",4,100000)

#flat
Ucrit_parent_fulldata_flatprior_10e5 <- model_run(prior_flat_params,'speed',"animal+clutch+dam+sire",4,100000)

#save them as a list
Ucrit_parent_fulldata_10e5 <- list(Ucrit_parent_fulldata_priorexpand_10e5,Ucrit_parent_fulldata_priorext_10e5,
                                  Ucrit_parent_fulldata_invgamma_10e5,Ucrit_parent_fulldata_invgamma2_10e5,
                                  Ucrit_parent_fulldata_flatprior_10e5)
save(Ucrit_parent_fulldata_10e5,file='../model_runs/Ucrit_parent_fulldata_10e5.RData')

```
## Trimmed dataset models

```{r, eval=FALSE}
### SL, no parental effects

#prior_expand
SL_noparent_trimdata_priorexpand_10e5 <- model_run(prior_expand_params,'length',"animal+clutch",2,100000)

#prior_ext
SL_noparent_trimdata_priorext_10e5 <- model_run(prior_ext_params,'length',"animal+clutch",2,100000)

#invgamma
SL_noparent_trimdata_invgamma_10e5 <- model_run(prior_invgamma_params,'length',"animal+clutch",2,100000)

#invgamma2
SL_noparent_trimdata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'length',"animal+clutch",2,100000)

#flat
SL_noparent_trimdata_flatprior_10e5 <- model_run(prior_flat_params,'length',"animal+clutch",2,100000)

#save them as a list
SL_noparent_trimdata_10e5 <- list(SL_noparent_trimdata_priorexpand_10e5,SL_noparent_trimdata_priorext_10e5,
                                  SL_noparent_trimdata_invgamma_10e5,SL_noparent_trimdata_invgamma2_10e5,
                                  SL_noparent_trimdata_flatprior_10e5)
save(SL_noparent_trimdata_10e5,file='../model_runs/SL_noparent_trimdata_10e5.RData')


### SL, with parental effects

#prior_expand
SL_parent_trimdata_priorexpand_10e5 <- model_run(prior_expand_params,'length',"animal+clutch+dam+sire",4,100000)

#prior_ext
SL_parent_trimdata_priorext_10e5 <- model_run(prior_ext_params,'length',"animal+clutch+dam+sire",4,100000)

#invgamma
SL_parent_trimdata_invgamma_10e5 <- model_run(prior_invgamma_params,'length',"animal+clutch+dam+sire",4,100000)

#invgamma2
SL_parent_trimdata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'length',"animal+clutch+dam+sire",4,100000)

#flat -- Error: "Mixed model equations singular: use a (stronger) prior"
#SL_parent_trimdata_flatprior_10e5 <- model_run(prior_flat_params,'length',"animal+clutch+dam+sire",4,100000)

#save them as a list
SL_parent_trimdata_10e5 <- list(SL_parent_trimdata_priorexpand_10e5,SL_parent_trimdata_priorext_10e5,
                                  SL_parent_trimdata_invgamma_10e5,SL_parent_trimdata_invgamma2_10e5)
save(SL_parent_trimdata_10e5,file='../model_runs/SL_parent_trimdata_10e5.RData')


### Ucrit, no parental effects

#prior_expand
Ucrit_noparent_trimdata_priorexpand_10e5 <- model_run(prior_expand_params,'speed',"animal+clutch",2,100000)

#prior_ext
Ucrit_noparent_trimdata_priorext_10e5 <- model_run(prior_ext_params,'speed',"animal+clutch",2,100000)

#invgamma
Ucrit_noparent_trimdata_invgamma_10e5 <- model_run(prior_invgamma_params,'speed',"animal+clutch",2,100000)

#invgamma2
Ucrit_noparent_trimdata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'speed',"animal+clutch",2,100000)

#flat
Ucrit_noparent_trimdata_flatprior_10e5 <- model_run(prior_flat_params,'speed',"animal+clutch",2,100000)

#save them as a list
Ucrit_noparent_trimdata_10e5 <- list(Ucrit_noparent_trimdata_priorexpand_10e5,Ucrit_noparent_trimdata_priorext_10e5,
                                  Ucrit_noparent_trimdata_invgamma_10e5,Ucrit_noparent_trimdata_invgamma2_10e5,
                                  Ucrit_noparent_trimdata_flatprior_10e5)
save(Ucrit_noparent_trimdata_10e5,file='../model_runs/Ucrit_noparent_trimdata_10e5.RData')


### Ucrit, with parental effects

#prior_expand
Ucrit_parent_trimdata_priorexpand_10e5 <- model_run(prior_expand_params,'speed',"animal+clutch+dam+sire",4,100000)

#prior_ext
Ucrit_parent_trimdata_priorext_10e5 <- model_run(prior_ext_params,'speed',"animal+clutch+dam+sire",4,100000)

#invgamma
Ucrit_parent_trimdata_invgamma_10e5 <- model_run(prior_invgamma_params,'speed',"animal+clutch+dam+sire",4,100000)

#invgamma2
Ucrit_parent_trimdata_invgamma2_10e5 <- model_run(prior_invgamma2_params,'speed',"animal+clutch+dam+sire",4,100000)

#flat
Ucrit_parent_trimdata_flatprior_10e5 <- model_run(prior_flat_params,'speed',"animal+clutch+dam+sire",4,100000)

#save them as a list
Ucrit_parent_trimdata_10e5 <- list(Ucrit_parent_trimdata_priorexpand_10e5,Ucrit_parent_trimdata_priorext_10e5,
                                  Ucrit_parent_trimdata_invgamma_10e5,Ucrit_parent_trimdata_invgamma2_10e5,
                                  Ucrit_parent_trimdata_flatprior_10e5)
save(Ucrit_parent_trimdata_10e5,file='../model_runs/Ucrit_parent_trimdata_10e5.RData')

```


### Run multiple chains for the best prior for each trait and model:

```{r}
prior_invgamma2 = list(R = list(V = 1, nu = 0.02),
             G = list(G1 = list(V = 1,nu = .02),
                      G2 = list(V = 1,nu = .02)))

start1=list(R=runif(1),G=c(runif(1),runif(1)))
start2=list(R=runif(1),G=c(runif(1),runif(1)))
start3=list(R=runif(1),G=c(runif(1),runif(1)))

SL_noparent_chain1 <- MCMCglmm(length~1+age,
                              random=~animal+clutch,
                              prior=prior_invgamma2,
                              start=start1,
                              ginverse=list(animal=Ainv),
                              data=phens,nitt=100000,burnin=1000,thin=10,verbose=TRUE)

SL_noparent_chain2 <- MCMCglmm(length~1+age,
                                random=~animal+clutch,
                                prior=prior_invgamma2,
                                start=start2,
                              ginverse=list(animal=Ainv),
                                data=phens,nitt=100000,burnin=1000,thin=10,verbose=TRUE)
SL_noparent_chain3 <- MCMCglmm(length~1+age,
                                random=~animal+clutch,
                                prior=prior_invgamma2,
                                start=start3,
                              ginverse=list(animal=Ainv),
                                data=phens,nitt=100000,burnin=1000,thin=10,verbose=TRUE)

SL_noparent_chains_fulldata <- list(SL_noparent_chain1,SL_noparent_chain2,SL_noparent_chain3)
save(SL_noparent_chains_fulldata,file='../model_runs/SL_noparent_chains_fulldata.RData')
```


